[package]
name = "shared-representation"
version = "0.1.0"
edition = "2021"

[dependencies]
petgraph = "0.6.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rayon = "1.5"
langchain = "0.2.2"
simba = "0.9.0"
